### ISSUE TITLE
Delegate for sharing on social media sites

### ISSUE THREAD

**Issue by danielkiedrowski** [Everyplay/everyplay-ios-sdk#12]
Hello.
I read this:

https://developers.everyplay.com/faq#everyplay-functionality_12.-is-it-possible-to-detect-when-the-user-shares-their-video-via-facebook/twitter/youtube,-so-we-can-reward-them?

I am unable to find delegate methods to implement, which notify me when the user shared a video on Facebook, YouTube or Twitter. I've just found the delegate methods to detect if the user uploaded a video.

Kind regards,
Daniel

**Comment by paugit** [comment]
You can detect a share by using the everyplayUploadDidComplete:(NSNumber *)videoId delegate method. Unfortunately it does expose the share type.
