### ISSUE TITLE
iOS: OpenAL interference

### ISSUE THREAD

**Issue by Shaderd00d** [Everyplay/everyplay-ios-sdk#29]
Hi,

I'm trying to integrate the SDK build 1840 and everything works fine besides OpenAL audio. Video recording and sharing works like a charm, but it seems to be impossible to hear audio on the device and record it at the same time.
When using supportsOpenAL = NO, I can hear audio from my device but it's not recorded. Using supportsOpenAL = YES, I can't hear audio on my device and there's also no audio recorded.
I've also tried older Everyplay builds down to 1.8.0 without success and use an iPad 2 with iOS 7.1.2 for testing.

Thanks in advance.

**Comment by aet** [comment]
sdk 1.9.5 is now out and it should fix the issue, thanks!
