### ISSUE TITLE
Hitting Share multiple times seems to bug out

### ISSUE THREAD

**Issue by davidc02** [Everyplay/everyplay-ios-sdk#30]
If I call PlayLastRecording(), then tap **Share**, then on the **Scissors** icon to trim the video, then **Share** again, the Everyplay interface rolls down out of the screen (like if I were closing it), but my game doesn't resume.

I just updated EveryPlay, this happens to me on iOS.

**Comment by paugit** [comment]
True, EveryplayHidden does not get called like it supposed to. Thanks for reporting. Hopefully there will be a fix for this in the next release.

**Comment by aet** [comment]
sdk 1.9.5 is now out and should fix this, thanks for info!
