### ISSUE TITLE
SpriteKit: View appears upside down in iOS 9.0

### ISSUE THREAD

**Issue by zsergey** [Everyplay/everyplay-ios-sdk#32]
![img_0045](https://cloud.githubusercontent.com/assets/1423911/8408494/3f3b6f10-1e79-11e5-9806-f236fe833abe.PNG)
Summary:
The SpriteKit scene is drawn upside down. This includes all child nodes and elements in the scene. Ads separate from the SKView are not drawn upside down.

**Comment by aet** [comment]
I didn't find any immediate issues after the first beta, was this against beta1 or beta2?

What was the SDK version used and device? Can you re-check against the just released 1.9.8 build?

Thanks

**Comment by zsergey** [comment]
Both (beta 1 and beta2). I made minimal SpriteKit game with latest Everyplay SDK. The problem appears only on a device with beta iOS 9. It works good in simulator.
https://github.com/zsergey/Test-Game-SpriteKit-iOS9

**Comment by aet** [comment]
thanks, i'll take a look at it during next week!

**Comment by zsergey** [comment]
thanks

**Comment by zsergey** [comment]
Hello. Have you fixed the problem? :)

**Comment by aet** [comment]
i was a bit optimistic on my time schedule and haven't had time to check the issue yet, sorry :) i think we're now at beta4 with ios9? should install it and check the issue again. it shouldn't be anything major to fix

**Comment by zsergey** [comment]
The issue is still reproducing on iOS 9 beta 4

**Comment by aet** [comment]
i've found the issue but as for the fix, not quite sure if it's an ios issue or should there be a workaround. i'll keep digging

**Comment by aet** [comment]
I can repeat the issue against SpriteKit Xcode sample project with just 3 lines of extra code,
so odds are it might be something that should be fixed to the final iOS 9. But while hoping
for that to happen, I made a workaround for it.. there should be a new SDK release out
by the end of next week. Thanks for your patience and reporting the issue

**Comment by zsergey** [comment]
Thank you!

**Comment by aet** [comment]
might need to postpone the release till early next week, few other ios9 issues came out that are generic and critical

**Comment by aet** [comment]
hi, finally got the release out. :) hope it works out for you, there were some last minute
App Transport Security (ATS) changes that we had to test
