### ISSUE TITLE
Error when trying to submit app on iOS9

### ISSUE THREAD

**Issue by obigu** [Everyplay/everyplay-ios-sdk#34]
Using Everyplay iOS custom engine version version 7.1.1.

When submitting app after updating to Xcode 7 and iOS 9 the following error message appears when trying to submit to AppStore:

ERROR ITMS-90535 "Unexpected CFBundleKey. The bundle at 'Payload/IOSLAuncher.app/Everyplay.bundle does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue"

**Comment by aet** [comment]
we'll do an upgrade during this week to get it fixed, thanks!

**Comment by aet** [comment]
should be ok now

**Comment by aet** [comment]
For solving the issue manually without SDK upgrade, running /usr/libexec/PlistBuddy -c "Delete CFBundleExecutable" Everyplay.bundle/Info.plist should be sufficient. But the current 2.0 and upcoming 2.0.1 fixes some important iOS 9 compatibility issues in general
