### ISSUE TITLE
ios9 records no audio

### ISSUE THREAD

**Issue by AGOG** [Everyplay/everyplay-ios-sdk#35]
After updating devices to ios9, Everyplay no longer records audio.

Everyplay v2000
Cocos2D-Swift version 3.4.3-develop
xCode v7.1
using OALAudio

audio is still recorded as normal on all devices < ios9

**Comment by aet** [comment]
It seems iOS9 broke a few things when using audio with OpenAL, AVFoundation :/
When used against Unity, it works as expected

We've got a fix release coming this week or by monday, thanks!

**Comment by aet** [comment]
2.0.1 sdk update is now out, along with iphone 6s specific fixes, thanks!
