### ISSUE TITLE
Upgrade warning appears in live app in iOS

### ISSUE THREAD

**Issue by furic** [Everyplay/everyplay-ios-sdk#37]
In document it said, "After expiring, there's a warning dialog on launch that recommends to upgrade the SDK. Apps downloaded from the App Store won't have this behaviour."

However the warning still appeared in my game which download from App Store.

I believe no developers want this warning to appear and confuse the players while no new game version is available yet.

Please take a look.

**Comment by paugit** [comment]
It is caused by faulty build type detection code in Everyplay SDK versions 2100 & 2110. A fix is already available. Please upgrade to Everyplay v2.1.2 - Sep 13th 2016 (build 2121). We are very sorry for the inconvenience.
